package com.mds.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "AVC")
public class Avc implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.Integer glasgowScore;

    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String irmResult;

    @org.kie.api.definition.type.Position(value = 3)
    private java.lang.Integer nihssScore;

    @org.kie.api.definition.type.Position(value = 0)
    private com.mds.beans.Triage triage;

    public Avc() {
    }
    
    public Avc(com.mds.beans.Triage triage, java.lang.String irmResult, java.lang.Integer glasgowScore, java.lang.Integer nihssScore) {
        this.triage = triage;
        this.irmResult = irmResult;
        this.glasgowScore = glasgowScore;
        this.nihssScore = nihssScore;
    }

    public java.lang.Integer getGlasgowScore() {
        return this.glasgowScore;
    }
    
    public void setGlasgowScore(java.lang.Integer glasgowScore) {
        this.glasgowScore = glasgowScore;
    }

    public java.lang.String getIrmResult() {
        return this.irmResult;
    }
    
    public void setIrmResult(java.lang.String irmResult) {
        this.irmResult = irmResult;
    }

    public java.lang.Integer getNihssScore() {
        return this.nihssScore;
    }
    
    public void setNihssScore(java.lang.Integer nihssScore) {
        this.nihssScore = nihssScore;
    }

    public com.mds.beans.Triage getTriage() {
        return this.triage;
    }
    
    public void setTriage(com.mds.beans.Triage triage) {
        this.triage = triage;
    }

}