package com.mds.model;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class MedicalRecords  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private java.util.List<com.mds.model.MedicalRecord> medicalRecords;

    public MedicalRecords() {
    }

    public MedicalRecords(java.util.List<com.mds.model.MedicalRecord> medicalRecords) {
        this.medicalRecords = medicalRecords;
    }


    
    public java.util.List<com.mds.model.MedicalRecord> getMedicalRecords() {
        return this.medicalRecords;
    }

    public void setMedicalRecords(  java.util.List<com.mds.model.MedicalRecord> medicalRecords ) {
        this.medicalRecords = medicalRecords;
    }
}