package com.mds.decisionsupport;

import com.mds.model.Contact;
import com.mds.model.InferenceResult;


rule "add description and remark to inference result and linke it to the contact triage 3"
	dialect "mvel"
	ruleflow-group "triage"
	no-loop true
	when
		$contact : Contact(  )
		$ir :InferenceResult( value == "3" )
	then
		 $ir.setOperation( "Triage" );
	       	 $ir.setDesciption( "Functional impairment or organic lesions likely to deteriorate within 24 h or complex medical situation justifying the use of several hospital resources" );
	         $ir.setRemark( "Multiple actions focused on diagnostic evaluation and prognostic evaluation in addition to treatment Medical intervention within 60 min ± followed by paramedical intervention" );
		$ir.setDate(new java.util.Date());
       		$contact.addInferenceResults($ir);
end
