package com.mds.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Vital Sign Monitoring Range")
public class VitalSignMonitoringRange implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "exam")
    @org.kie.api.definition.type.Position(value = 0)
    private com.mds.beans.SimpleExam exam;

    public VitalSignMonitoringRange() {
    }
    
    public VitalSignMonitoringRange(com.mds.beans.SimpleExam exam) {
        this.exam = exam;
    }

    public com.mds.beans.SimpleExam getExam() {
        return this.exam;
    }
    
    public void setExam(com.mds.beans.SimpleExam exam) {
        this.exam = exam;
    }

}