package mds.neurology;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Patient implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "first name")
   @org.kie.api.definition.type.Position(value = 1)
   private java.lang.String firstName;
   @org.kie.api.definition.type.Label(value = "last name")
   @org.kie.api.definition.type.Position(value = 2)
   private java.lang.String lastName;
   @org.kie.api.definition.type.Label(value = "birth date")
   @org.kie.api.definition.type.Position(value = 3)
   private java.util.Date birthDate;
   @org.kie.api.definition.type.Label(value = "id")
   @org.kie.api.definition.type.Position(value = 0)
   private java.lang.Long id;

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.util.Date getBirthDate()
   {
      return this.birthDate;
   }

   public void setBirthDate(java.util.Date birthDate)
   {
      this.birthDate = birthDate;
   }

   public java.lang.Long getId()
   {
      return this.id;
   }

   public void setId(java.lang.Long id)
   {
      this.id = id;
   }

   public Patient()
   {
   }

   public Patient(java.lang.Long id, java.lang.String firstName,
         java.lang.String lastName, java.util.Date birthDate)
   {
      this.id = id;
      this.firstName = firstName;
      this.lastName = lastName;
      this.birthDate = birthDate;
   }

}