package com.mds.myhealth;

import com.mds.myhealth.Patient;
import com.mds.myhealth.SimpleExam;
import java.util.List;

rule "UpdatePatient"
dialect "mvel"
ruleflow-group "PatientMonitoring"
when
myPatient1 :  Patient(examsList1 : exams )
myPatient2: Patient( this != myPatient1 , id == myPatient1.getId(), examsList2 : exams  )
then
examsList1.addAll(examsList2);
 modify( myPatient1) {
	setExams(examsList1)
}
 retract( myPatient2);
System.out.println("update patient rule !");
end