package com.mds.beans;

import com.mds.beans.Triage;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("AVC")
public class Avc extends Triage implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Position(1)
	private java.lang.Integer glasgowScore;

    @org.kie.api.definition.type.Position(0)
	private java.lang.String irmResult;

    @org.kie.api.definition.type.Position(2)
	private java.lang.Integer nihssScore;

    @org.kie.api.definition.type.Position(3)
   	private java.lang.String patientidentity;    
    
    public java.lang.Integer getGlasgowScore() {
        return this.glasgowScore;
    }
    
    public void setGlasgowScore(java.lang.Integer glasgowScore) {
        this.glasgowScore = glasgowScore;
    }

    public java.lang.String getIrmResult() {
        return this.irmResult;
    }
    
    public void setIrmResult(java.lang.String irmResult) {
        this.irmResult = irmResult;
    }

    public java.lang.Integer getNihssScore() {
        return this.nihssScore;
    }
    
    public void setNihssScore(java.lang.Integer nihssScore) {
        this.nihssScore = nihssScore;
    }

    
    public Avc() {
	}

    public Avc(com.mds.beans.Triage triage) {
    	this.patient = triage.getPatient();
		this.contact = triage.getContact();
		this.pamiList = triage.getPamiList();
		this.triageValue = triage.getTriageValue();
		this.triageDescription = triage.getTriageDescription();
		this.triageDate =triage.getTriageDate();
		this.suggestions = triage.getSuggestions();
		this.adoptedSuggestion =triage.getAdoptedSuggestion();
		this.startTheSelectedClinicalPathway = triage.getStartTheSelectedClinicalPathway();
		if(triage.getPatient() != null  && triage.getPatient().getFirstName() != null && triage.getPatient().getLastName() != null)
			this.patientidentity = triage.getPatient().getFirstName()+" "+triage.getPatient().getLastName();
   	}
    
	public Avc(java.lang.String irmResult, java.lang.Integer glasgowScore,
			java.lang.Integer nihssScore) {
		this.irmResult = irmResult;
		this.glasgowScore = glasgowScore;
		this.nihssScore = nihssScore;
	}

	@Override
	public String toString() {
		return "Avc [glasgowScore=" + glasgowScore + ", irmResult=" + irmResult
				+ ", nihssScore=" + nihssScore + ", patientidentity="
				+ patientidentity + ", contact=" + contact + ", patient="
				+ patient + ", pamiList=" + pamiList + ", triageValue="
				+ triageValue + ", triageDescription=" + triageDescription
				+ ", triageDate=" + triageDate + ", suggestions=" + suggestions
				+ ", adoptedSuggestion=" + adoptedSuggestion
				+ ", startTheSelectedClinicalPathway="
				+ startTheSelectedClinicalPathway + "]";
	}

	
	
	
}