package com.mds.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MonitoringRange implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "action")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String action;

    @org.kie.api.definition.type.Label(value = "max")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Integer max;

    @org.kie.api.definition.type.Label(value = "min")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.Integer min;

    public MonitoringRange() {
    }
    
    public MonitoringRange(java.lang.Integer min, java.lang.Integer max, java.lang.String action) {
        this.min = min;
        this.max = max;
        this.action = action;
    }

    public java.lang.String getAction() {
        return this.action;
    }
    
    public void setAction(java.lang.String action) {
        this.action = action;
    }

    public java.lang.Integer getMax() {
        return this.max;
    }
    
    public void setMax(java.lang.Integer max) {
        this.max = max;
    }

    public java.lang.Integer getMin() {
        return this.min;
    }
    
    public void setMin(java.lang.Integer min) {
        this.min = min;
    }

	@Override
	public String toString() {
		return "MonitoringRange [action=" + action + ", max=" + max + ", min="
				+ min + "]";
	}

}