package com.mds.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Triage implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    
    @org.kie.api.definition.type.Position(1)
	protected com.mds.beans.Contact contact;

    @org.kie.api.definition.type.Position(0)
    protected com.mds.beans.Patient patient;

    @org.kie.api.definition.type.Position(2)
    protected java.util.List<com.mds.beans.Pami> pamiList;

	@org.kie.api.definition.type.Label("triage value")
	@org.kie.api.definition.type.Position(3)
	protected java.lang.String triageValue;

	@org.kie.api.definition.type.Label("Triage description")
	@org.kie.api.definition.type.Position(4)
	protected java.lang.String triageDescription;

	@org.kie.api.definition.type.Label("triage date")
	@org.kie.api.definition.type.Position(5)
	protected java.util.Date triageDate;

	@org.kie.api.definition.type.Label(value = "Suggestions")
	@org.kie.api.definition.type.Position(value = 6)
	protected java.util.List<com.mds.beans.TriageSuggestion> suggestions;

	@org.kie.api.definition.type.Label(value = "adopted suggestion")
	@org.kie.api.definition.type.Position(value = 7)
	protected com.mds.beans.TriageSuggestion adoptedSuggestion;

	@org.kie.api.definition.type.Label(value = "start the selected clinical pathway")
	@org.kie.api.definition.type.Position(value = 8)
	protected java.lang.Boolean startTheSelectedClinicalPathway;

	public com.mds.beans.Contact getContact() {
        return this.contact;
    }
    
    public void setContact(com.mds.beans.Contact contact) {
        this.contact = contact;
    }

    public com.mds.beans.Patient getPatient() {
        return this.patient;
    }
    
    public void setPatient(com.mds.beans.Patient patient) {
        this.patient = patient;
    }

    public java.util.List<com.mds.beans.Pami> getPamiList() {
		return this.pamiList;
	}

	public void setPamiList(java.util.List<com.mds.beans.Pami> pamiList) {
		this.pamiList = pamiList;
	}

	public java.lang.String getTriageValue() {
		return this.triageValue;
	}

	public void setTriageValue(java.lang.String triageValue) {
		this.triageValue = triageValue;
	}

	public java.lang.String getTriageDescription() {
		return this.triageDescription;
	}

	public void setTriageDescription(java.lang.String triageDescription) {
		this.triageDescription = triageDescription;
	}

	public java.util.Date getTriageDate() {
		return this.triageDate;
	}

	public void setTriageDate(java.util.Date triageDate) {
		this.triageDate = triageDate;
	}

	public java.util.List<com.mds.beans.TriageSuggestion> getSuggestions() {
		return this.suggestions;
	}

	public void setSuggestions(
			java.util.List<com.mds.beans.TriageSuggestion> suggestions) {
		this.suggestions = suggestions;
	}
	
	public void addSuggestions(com.mds.beans.TriageSuggestion suggestion) {
		if(this.suggestions == null)
			this.suggestions = new java.util.ArrayList<com.mds.beans.TriageSuggestion>();
		this.suggestions.add(suggestion);
	}
	
	public void addSuggestions(java.lang.String value, java.lang.String suggestionClinicalPathway, java.lang.String suggestionClinicalPathwayID) {
		if(this.suggestions == null)
			this.suggestions = new java.util.ArrayList<com.mds.beans.TriageSuggestion>();
		this.suggestions.add(new TriageSuggestion(value, suggestionClinicalPathway, suggestionClinicalPathwayID));		
	}

	public com.mds.beans.TriageSuggestion getAdoptedSuggestion() {
		return this.adoptedSuggestion;
	}

	public void setAdoptedSuggestion(
			com.mds.beans.TriageSuggestion adoptedSuggestion) {
		this.adoptedSuggestion = adoptedSuggestion;
	}

	public java.lang.Boolean getStartTheSelectedClinicalPathway() {
		return this.startTheSelectedClinicalPathway;
	}

	public void setStartTheSelectedClinicalPathway(
			java.lang.Boolean startTheSelectedClinicalPathway) {
		this.startTheSelectedClinicalPathway = startTheSelectedClinicalPathway;
	}

	public Triage() {
	}

	public Triage(com.mds.beans.Patient patient, com.mds.beans.Contact contact,
			java.util.List<com.mds.beans.Pami> pamiList,
			java.lang.String triageValue, java.lang.String triageDescription,
			java.util.Date triageDate,
			java.util.List<com.mds.beans.TriageSuggestion> suggestions,
			com.mds.beans.TriageSuggestion adoptedSuggestion,
			java.lang.Boolean startTheSelectedClinicalPathway) {
		this.patient = patient;
		this.contact = contact;
		this.pamiList = pamiList;
		this.triageValue = triageValue;
		this.triageDescription = triageDescription;
		this.triageDate = triageDate;
		this.suggestions = suggestions;
		this.adoptedSuggestion = adoptedSuggestion;
		this.startTheSelectedClinicalPathway = startTheSelectedClinicalPathway;
	}

	@Override
	public String toString() {
		return "pamiList=" + pamiList +" <br> patient=" + patient+ " <br>,contact=" + contact + ", pamiList=" + pamiList + ", triageValue=" + triageValue
				+ ", triageDescription=" + triageDescription + ", triageDate="
				+ triageDate + ", suggestions=" + suggestions
				+ ", adoptedSuggestion=" + adoptedSuggestion
				+ ", startTheSelectedClinicalPathway="
				+ startTheSelectedClinicalPathway;
	}

	
	
}