package com.mds.beans;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Vital Sign Monitoring Range")
public class VitalSignMonitoringRange implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("exam")
	@org.kie.api.definition.type.Position(0)
	private com.mds.beans.SimpleExam exam;

    @org.kie.api.definition.type.Label(value = "range")
	@org.kie.api.definition.type.Position(value = 1)
	private java.util.List<com.mds.beans.MonitoringRange> range;

	public com.mds.beans.SimpleExam getExam() {
        return this.exam;
    }
    
    public void setExam(com.mds.beans.SimpleExam exam) {
        this.exam = exam;
    }

	public java.util.List<com.mds.beans.MonitoringRange> getRange() {
		return this.range;
	}

	public void setRange(java.util.List<com.mds.beans.MonitoringRange> range) {
		this.range = range;
	}

	public VitalSignMonitoringRange() {
	}

	public VitalSignMonitoringRange(com.mds.beans.SimpleExam exam,
			java.util.List<com.mds.beans.MonitoringRange> range) {
		this.exam = exam;
		this.range = range;
	}

}