package com.mds.beans;

import java.util.ArrayList;
import java.util.List;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Vital Sign Monitoring Range")
public class VitalSignMonitoring extends SimpleExam implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("ranges")
	@org.kie.api.definition.type.Position(0)
	private java.util.List<com.mds.beans.MonitoringRange> ranges;


	@org.kie.api.definition.type.Label("in range")
	@org.kie.api.definition.type.Position(1)
	private com.mds.beans.MonitoringRange inRange;

	
	@org.kie.api.definition.type.Label("message")
	@org.kie.api.definition.type.Position(2)
	private java.lang.String msg;


	@org.kie.api.definition.type.Label("is Monitored")
	@org.kie.api.definition.type.Position(3)
	private java.lang.Boolean isMonitored = false;

	
	public java.lang.Boolean getIsMonitored() {
		return isMonitored;
	}

	public void setIsMonitored(java.lang.Boolean isMonitored) {
		this.isMonitored = isMonitored;
	}

	public java.lang.String getMsg() {
		return msg;
	}

	public void setMsg(java.lang.String msg) {
		this.msg = msg;
	}

	public java.util.List<com.mds.beans.MonitoringRange> getRanges() {
		return this.ranges;
	}

	public void setRanges(java.util.List<com.mds.beans.MonitoringRange> ranges) {
		this.ranges = ranges;
	}

	public void addRange(com.mds.beans.MonitoringRange range)
	{
		if(ranges == null)
		{
			this.ranges = new ArrayList<MonitoringRange>();
		}
		ranges.add(range);
	}

	@Override
	public String toString() {
		return "VitalSignMonitoring [ranges=" + ranges + ", getNValue()="
				+ getNValue() + ", getMiText()=" + getMiText()
				+ ", getMiDate()=" + getMiDate() + "]";
	}

	public com.mds.beans.MonitoringRange getInRange() {
		return this.inRange;
	}

	public void setInRange(com.mds.beans.MonitoringRange inRange) {
		this.inRange = inRange;
	}

	public VitalSignMonitoring() {
	}

	public VitalSignMonitoring(
			java.util.List<com.mds.beans.MonitoringRange> ranges,
			com.mds.beans.MonitoringRange inRange) {
		this.ranges = ranges;
		this.inRange = inRange;
	}

	public VitalSignMonitoring(Double nValue, String sValue, String unit,
			List<MonitoringRange> ranges, MonitoringRange inRange, String msg,
			Boolean isMonitored) {
		super(nValue, sValue, unit);
		this.ranges = ranges;
		this.inRange = inRange;
		this.msg = msg;
		this.isMonitored = isMonitored;
	}
	
	
}