package com.mds.decisionsupport;
import com.mds.beans.Pami;
import com.mds.beans.Triage;
import com.mds.beans.TriageSuggestion;
import com.mds.beans.Avc;


rule "AvcIschemicTreatment"
		dialect "mvel"
	   	ruleflow-group "avcIschemicTreatment"
	       salience 1
when
	avcBean : com.mds.beans.Avc( Pami( miCode in ( "http://snomed.info/id/371632003" ))  not memberOf pamiList )
then
System.out.println("test");
end