package com.mds.monitoring;

import java.lang.Number;
import com.mds.beans.SimpleExam;
import com.mds.beans.Monitoring;
import com.mds.beans.MonitoringRange;
import com.mds.beans.VitalSignMonitoring;
	
rule "InsertingMonitoringData"
	    dialect "mvel"
	    ruleflow-group "monitoring"	    
	    lock-on-active true
	    salience 10
	    when
	        $monitoringBean : Monitoring( $items : items  != null )
	        $vitalSign : VitalSignMonitoring() from $items
	    then
	      System.out.println("Inserting ");
	      insert($vitalSign);	       
end

rule "monitoringRule"
	    dialect "mvel"
	    ruleflow-group "monitoring"	    
	    lock-on-active true
	    salience 5
	    when
	        $vitalSign : VitalSignMonitoring( $ranges : ranges != null, $value : NValue )
	        $range : 	MonitoringRange($value >= min , $value <= max ) from $ranges	
	    then
	      System.out.println("Monitoring rule triggred : "+$range.action);	       
end