package com.mds;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Monitoring")
public class Monitoring implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Monitoring() {
    }

}