package com.mds.myhealth;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Patient")
@org.kie.api.definition.type.TypeSafe(true)
public class Patient implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Key
   @org.kie.api.definition.type.Label("First name")
   @org.kie.api.definition.type.Position(0)
   private java.lang.String firstName;

   @org.kie.api.definition.type.Key
   @org.kie.api.definition.type.Label("Last name")
   @org.kie.api.definition.type.Position(1)
   private java.lang.String lastName;

   @org.kie.api.definition.type.Key
   @org.kie.api.definition.type.Label("patient id")
   @org.kie.api.definition.type.Position(2)
   private String id;

   @org.kie.api.definition.type.Key
   @org.kie.api.definition.type.Label("Exams")
   @org.kie.api.definition.type.Position(3)
   private java.util.List<com.mds.myhealth.SimpleExam> exams;

   @org.kie.api.definition.type.Label("Birth date")
   @org.kie.api.definition.type.Position(4)
   private java.util.Date birthDate;

   public java.lang.String getFirstName()
   {
      return this.firstName;
   }

   public void setFirstName(java.lang.String firstName)
   {
      this.firstName = firstName;
   }

   public java.lang.String getLastName()
   {
      return this.lastName;
   }

   public void setLastName(java.lang.String lastName)
   {
      this.lastName = lastName;
   }

   public java.util.List<com.mds.myhealth.SimpleExam> getExams()
   {
      return this.exams;
   }

   public void setExams(java.util.List<com.mds.myhealth.SimpleExam> exams)
   {
      this.exams = exams;
   }

   public java.util.Date getBirthDate()
   {
      return this.birthDate;
   }

   public void setBirthDate(java.util.Date birthDate)
   {
      this.birthDate = birthDate;
   }

   public java.lang.String getId()
   {
      return this.id;
   }

   public void setId(java.lang.String id)
   {
      this.id = id;
   }

   public Patient()
   {
   }

   public Patient(java.lang.String firstName, java.lang.String lastName,
         java.lang.String id, java.util.List<com.mds.myhealth.SimpleExam> exams,
         java.util.Date birthDate)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.id = id;
      this.exams = exams;
      this.birthDate = birthDate;
   }

   public Patient(java.lang.String firstName, java.lang.String lastName,
         java.lang.String id, java.util.List<com.mds.myhealth.SimpleExam> exams)
   {
      this.firstName = firstName;
      this.lastName = lastName;
      this.id = id;
      this.exams = exams;
   }

   @Override
   public boolean equals(Object o)
   {
      if (this == o)
         return true;
      if (o == null || getClass() != o.getClass())
         return false;
      com.mds.myhealth.Patient that = (com.mds.myhealth.Patient) o;
      if (exams != null ? !exams.equals(that.exams) : that.exams != null)
         return false;
      if (firstName != null ? !firstName.equals(that.firstName)
            : that.firstName != null)
         return false;
      if (id != null ? !id.equals(that.id) : that.id != null)
         return false;
      if (lastName != null ? !lastName.equals(that.lastName)
            : that.lastName != null)
         return false;
      return true;
   }

   @Override
   public int hashCode()
   {
      int result = 17;
      result = 31 * result + (exams != null ? exams.hashCode() : 0);
      result = 31 * result + (firstName != null ? firstName.hashCode() : 0);
      result = 31 * result + (id != null ? id.hashCode() : 0);
      result = 31 * result + (lastName != null ? lastName.hashCode() : 0);
      return result;
   }

}