package com.mds.myhealth;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Simple exam")
@org.kie.api.definition.type.TypeSafe(true)
@org.kie.api.definition.type.Timestamp("date")
public class SimpleExam implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label("exam name")
   @org.kie.api.definition.type.Position(0)
   @org.kie.api.definition.type.Key
   private java.lang.String name;
   @org.kie.api.definition.type.Label("StringValue")
   @org.kie.api.definition.type.Position(1)
   @org.kie.api.definition.type.Key
   private java.lang.String sValue;
   @org.kie.api.definition.type.Label("int value")
   @org.kie.api.definition.type.Position(2)
   @org.kie.api.definition.type.Key
   private Long intValue;
   @org.kie.api.definition.type.Label("double value")
   @org.kie.api.definition.type.Position(3)
   @org.kie.api.definition.type.Key
   private java.lang.Double doubleValue;
   @org.kie.api.definition.type.Label("date")
   @org.kie.api.definition.type.Position(4)
   @org.kie.api.definition.type.Key
   private java.util.Date date;

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getsValue()
   {
      return this.sValue;
   }

   public void setsValue(java.lang.String sValue)
   {
      this.sValue = sValue;
   }

   public java.lang.Double getDoubleValue()
   {
      return this.doubleValue;
   }

   public void setDoubleValue(java.lang.Double doubleValue)
   {
      this.doubleValue = doubleValue;
   }

   public java.util.Date getDate()
   {
      return this.date;
   }

   public void setDate(java.util.Date date)
   {
      this.date = date;
   }

   public java.lang.Long getIntValue()
   {
      return this.intValue;
   }

   public void setIntValue(java.lang.Long intValue)
   {
      this.intValue = intValue;
   }

   public SimpleExam()
   {
   }

   public SimpleExam(java.lang.String name, java.lang.String sValue,
         java.lang.Long intValue, java.lang.Double doubleValue,
         java.util.Date date)
   {
      this.name = name;
      this.sValue = sValue;
      this.intValue = intValue;
      this.doubleValue = doubleValue;
      this.date = date;
   }

   @Override
   public boolean equals(Object o)
   {
      if (this == o)
         return true;
      if (o == null || getClass() != o.getClass())
         return false;
      com.mds.myhealth.SimpleExam that = (com.mds.myhealth.SimpleExam) o;
      if (date != null ? !date.equals(that.date) : that.date != null)
         return false;
      if (doubleValue != null ? !doubleValue.equals(that.doubleValue)
            : that.doubleValue != null)
         return false;
      if (intValue != null ? !intValue.equals(that.intValue)
            : that.intValue != null)
         return false;
      if (name != null ? !name.equals(that.name) : that.name != null)
         return false;
      if (sValue != null ? !sValue.equals(that.sValue) : that.sValue != null)
         return false;
      return true;
   }

   @Override
   public int hashCode()
   {
      int result = 17;
      result = 31 * result + (date != null ? date.hashCode() : 0);
      result = 31 * result + (doubleValue != null ? doubleValue.hashCode() : 0);
      result = 31 * result + (intValue != null ? intValue.hashCode() : 0);
      result = 31 * result + (name != null ? name.hashCode() : 0);
      result = 31 * result + (sValue != null ? sValue.hashCode() : 0);
      return result;
   }

}