package com.mds;

import com.mds.model.medical.item.Assessment;

/**
 * This class was automatically generated by the data modeler tool.
 */
public class Assessments  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private java.util.List<Assessment> assessments;

    public Assessments() {
    }

    public Assessments(java.util.List<Assessment> assessments) {
        this.assessments = assessments;
    }


    
    public java.util.List<Assessment> getAssessments() {
        return this.assessments;
    }

    public void setAssessments(  java.util.List<Assessment> assessments ) {
        this.assessments = assessments;
    }
}