package com.mds;

import com.mds.model.medical.item.objective.ObjectiveImpl;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Objectives  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private java.util.List<ObjectiveImpl> objectives;

    public Objectives() {
    }

    public Objectives(java.util.List<ObjectiveImpl> objectives) {
        this.objectives = objectives;
    }


    
    public java.util.List<ObjectiveImpl> getObjectives() {
        return this.objectives;
    }

    public void setObjectives(  java.util.List<ObjectiveImpl> objectives ) {
        this.objectives = objectives;
    }
}