package com.mds;

import com.mds.model.medical.item.Plan;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Plans  implements java.io.Serializable {

static final long serialVersionUID = 1L;
    
    private java.util.List<Plan> plans;

    public Plans() {
    }

    public Plans(java.util.List<Plan> plans) {
        this.plans = plans;
    }


    
    public java.util.List<Plan> getPlans() {
        return this.plans;
    }

    public void setPlans(  java.util.List<Plan> plans ) {
        this.plans = plans;
    }
}