package com.mds;

import com.mds.model.medical.item.Subjective;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Subjectives  implements java.io.Serializable {

static final long serialVersionUID = 1L;

	private java.util.List<Subjective> subjectives;

    public Subjectives() {
    }

    public Subjectives(java.util.List<Subjective> subjectives) {
        this.subjectives = subjectives;
    }


    
    public java.util.List<Subjective> getSubjectives() {
        return this.subjectives;
    }

    public void setSubjectives(  java.util.List<Subjective> subjectives ) {
        this.subjectives = subjectives;
    }
}