package cdss;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Diagnosis")
public class Diagnosis implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("Date")
	@org.kie.api.definition.type.Position(1)
	private java.lang.String date;

    @org.kie.api.definition.type.Label("Value")
	@org.kie.api.definition.type.Position(0)
	private java.lang.String value;

    @org.kie.api.definition.type.Label(value = "Dr agreement")
	@org.kie.api.definition.type.Position(value = 2)
	private java.lang.Boolean drAgreement;

	public java.lang.String getDate() {
        return this.date;
    }
    
    public void setDate(java.lang.String date) {
        this.date = date;
    }

    public java.lang.String getValue() {
        return this.value;
    }
    
    public void setValue(java.lang.String value) {
        this.value = value;
    }

	public java.lang.Boolean getDrAgreement() {
		return this.drAgreement;
	}

	public void setDrAgreement(java.lang.Boolean drAgreement) {
		this.drAgreement = drAgreement;
	}

	public Diagnosis() {
	}

	public Diagnosis(java.lang.String value, java.lang.String date,
			java.lang.Boolean drAgreement) {
		this.value = value;
		this.date = date;
		this.drAgreement = drAgreement;
	}

}