package cdss;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Patient record")
public class PatientRecord implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Assignement")
    @org.kie.api.definition.type.Position(value = 5)
    private cdss.Assignement assignement;

    @org.kie.api.definition.type.Label(value = "Birth date")
    @org.kie.api.definition.type.Position(value = 2)
    private java.util.Date birthDate;

    @org.kie.api.definition.type.Label(value = "Diagnoses")
    @org.kie.api.definition.type.Position(value = 4)
    private java.util.List<cdss.Diagnosis> diagnoses;

    @org.kie.api.definition.type.Label(value = "First name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String firstName;

    @org.kie.api.definition.type.Label(value = "Last name")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.String lastName;

    @org.kie.api.definition.type.Label(value = "Medical examinations")
    @org.kie.api.definition.type.Position(value = 8)
    private java.util.List<cdss.MedicalExamination> medicalExaminations;

    @org.kie.api.definition.type.Label(value = "Symptoms")
    @org.kie.api.definition.type.Position(value = 6)
    private java.util.List<cdss.Symptom> symptoms;

    @org.kie.api.definition.type.Label(value = "Treatments")
    @org.kie.api.definition.type.Position(value = 7)
    private java.util.List<cdss.Treatment> treatments;

    @org.kie.api.definition.type.Label(value = "Vital Signs")
    @org.kie.api.definition.type.Position(value = 3)
    private java.util.List<cdss.VitalSign> vitalSigns;

    public PatientRecord() {
    }
    
    public PatientRecord(java.lang.String firstName, java.lang.String lastName, java.util.Date birthDate, java.util.List<cdss.VitalSign> vitalSigns, java.util.List<cdss.Diagnosis> diagnoses, cdss.Assignement assignement, java.util.List<cdss.Symptom> symptoms, java.util.List<cdss.Treatment> treatments, java.util.List<cdss.MedicalExamination> medicalExaminations) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.birthDate = birthDate;
        this.vitalSigns = vitalSigns;
        this.diagnoses = diagnoses;
        this.assignement = assignement;
        this.symptoms = symptoms;
        this.treatments = treatments;
        this.medicalExaminations = medicalExaminations;
    }

    public cdss.Assignement getAssignement() {
        return this.assignement;
    }
    
    public void setAssignement(cdss.Assignement assignement) {
        this.assignement = assignement;
    }

    public java.util.Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(java.util.Date birthDate) {
        this.birthDate = birthDate;
    }

    public java.util.List<cdss.Diagnosis> getDiagnoses() {
        return this.diagnoses;
    }
    
    public void setDiagnoses(java.util.List<cdss.Diagnosis> diagnoses) {
        this.diagnoses = diagnoses;
    }

    public java.lang.String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(java.lang.String firstName) {
        this.firstName = firstName;
    }

    public java.lang.String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(java.lang.String lastName) {
        this.lastName = lastName;
    }

    public java.util.List<cdss.MedicalExamination> getMedicalExaminations() {
        return this.medicalExaminations;
    }
    
    public void setMedicalExaminations(java.util.List<cdss.MedicalExamination> medicalExaminations) {
        this.medicalExaminations = medicalExaminations;
    }

    public java.util.List<cdss.Symptom> getSymptoms() {
        return this.symptoms;
    }
    
    public void setSymptoms(java.util.List<cdss.Symptom> symptoms) {
        this.symptoms = symptoms;
    }

    public java.util.List<cdss.Treatment> getTreatments() {
        return this.treatments;
    }
    
    public void setTreatments(java.util.List<cdss.Treatment> treatments) {
        this.treatments = treatments;
    }

    public java.util.List<cdss.VitalSign> getVitalSigns() {
        return this.vitalSigns;
    }
    
    public void setVitalSigns(java.util.List<cdss.VitalSign> vitalSigns) {
        this.vitalSigns = vitalSigns;
    }

}