package cdss;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Symptom")
public class Symptom implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Date")
    @org.kie.api.definition.type.Position(value = 1)
    private java.util.Date date;

    @org.kie.api.definition.type.Label(value = "Description")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String description;

    public Symptom() {
    }
    
    public Symptom(java.lang.String description, java.util.Date date) {
        this.description = description;
        this.date = date;
    }

    public java.util.Date getDate() {
        return this.date;
    }
    
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public java.lang.String getDescription() {
        return this.description;
    }
    
    public void setDescription(java.lang.String description) {
        this.description = description;
    }

}