package cdss;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label(value = "Vital sign")
public class VitalSign implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label(value = "Date")
    @org.kie.api.definition.type.Position(value = 3)
    private java.util.Date date;

    @org.kie.api.definition.type.Label(value = "Name")
    @org.kie.api.definition.type.Position(value = 0)
    private java.lang.String name;

    @org.kie.api.definition.type.Label(value = "Unit")
    @org.kie.api.definition.type.Position(value = 2)
    private java.lang.String unit;

    @org.kie.api.definition.type.Label(value = "Value")
    @org.kie.api.definition.type.Position(value = 1)
    private java.lang.Float value;

    public VitalSign() {
    }
    
    public VitalSign(java.lang.String name, java.lang.Float value, java.lang.String unit, java.util.Date date) {
        this.name = name;
        this.value = value;
        this.unit = unit;
        this.date = date;
    }

    public java.util.Date getDate() {
        return this.date;
    }
    
    public void setDate(java.util.Date date) {
        this.date = date;
    }

    public java.lang.String getName() {
        return this.name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }

    public java.lang.String getUnit() {
        return this.unit;
    }
    
    public void setUnit(java.lang.String unit) {
        this.unit = unit;
    }

    public java.lang.Float getValue() {
        return this.value;
    }
    
    public void setValue(java.lang.Float value) {
        this.value = value;
    }

}