package cdss;

/**
 * This class was automatically generated by the data modeler tool.
 */

@org.kie.api.definition.type.Label("Vital parameter measurement")
public class VitalParameterMeasurement implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    @org.kie.api.definition.type.Label("Name")
	@org.kie.api.definition.type.Position(0)
	private java.lang.String name;

    @org.kie.api.definition.type.Label(value = "Nurse agreement")
	@org.kie.api.definition.type.Position(value = 1)
	private java.lang.Boolean nurseAgreement;

	public java.lang.String getName() {
        return this.name;
    }
    
    public void setName(java.lang.String name) {
        this.name = name;
    }

	public java.lang.Boolean getNurseAgreement() {
		return this.nurseAgreement;
	}

	public void setNurseAgreement(java.lang.Boolean nurseAgreement) {
		this.nurseAgreement = nurseAgreement;
	}

	public VitalParameterMeasurement() {
	}

	public VitalParameterMeasurement(java.lang.String name,
			java.lang.Boolean nurseAgreement) {
		this.name = name;
		this.nurseAgreement = nurseAgreement;
	}

}